spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  cache:
    type: simple
